// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sovereign.Infrastructure.Persistence;

#nullable disable

namespace Sovereign.Infrastructure.Migrations
{
    [DbContext(typeof(SovereignDbContext))]
    partial class SovereignDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sovereign.Domain.Aggregates.Relationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContactId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<double>("EmotionalTemperature")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("LastInteractionAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("MomentumScore")
                        .HasColumnType("double precision");

                    b.Property<double>("PowerDifferential")
                        .HasColumnType("double precision");

                    b.Property<double>("ReciprocityScore")
                        .HasColumnType("double precision");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("LastInteractionAtUtc");

                    b.HasIndex("UserId", "ContactId")
                        .IsUnique();

                    b.ToTable("relationships", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
